Class {
	#name : 'CzGreenThemeConfigurator',
	#superclass : 'ColoredBasedThemeConfigurator',
	#category : 'CozyPalettedThemes-Strong',
	#package : 'CozyPalettedThemes',
	#tag : 'Strong'
}

{ #category : 'accessing' }
CzGreenThemeConfigurator >> baseColor [
	^ Color fromHexString: '1F774D'
]

{ #category : 'accessing' }
CzGreenThemeConfigurator >> selectionColor [
	^ Color fromHexString: '1F774D'
]
